Jahia/saml-authentication-valve

src/main/java/org/jahia/modules/saml2/SAML2Util.java
src/main/resources/META-INF/configurations/org.jahia.modules.jahiacsrfguard-saml.cfg

https://jira.jahia.org/browse/BACKLOG-13899

BACKLOG-13899: Fixed csrf and port redirect

---

src/main/java/org/jahia/modules/saml2/SAML2Util.java
src/main/java/org/jahia/modules/saml2/actions/SAMLCallback.java
src/main/java/org/jahia/modules/saml2/admin/SAML2SettingsAction.java

https://jira.jahia.org/browse/BACKLOG-14233

BACKLOG-14233 - Improved error handling

---

src/main/java/org/jahia/modules/saml2/actions/SAMLCallback.java
src/main/java/org/jahia/modules/saml2/admin/SAML2SettingsAction.java

https://jira.jahia.org/browse/BACKLOG-14233

BACKLOG-14233: Small fixes

---

src/main/java/org/jahia/modules/saml2/SAML2Constants.java
src/main/java/org/jahia/modules/saml2/SAML2Util.java
src/main/java/org/jahia/modules/saml2/admin/SAML2Settings.java
src/main/java/org/jahia/modules/saml2/admin/SAML2SettingsAction.java
src/main/java/org/jahia/modules/saml2/admin/SAML2SettingsService.java
src/main/resources/javascript/i18n/saml-authentication-valve-i18n.js
src/main/resources/javascript/saml2/directives/settings/ma-settings.html

https://jira.jahia.org/browse/BACKLOG-14661

BACKLOG-14661: Add field to set user id

---

src/main/resources/javascript/saml2/directives/settings/ma-settings.html
src/main/resources/resources/saml-authentication-valve.properties

https://jira.jahia.org/browse/BACKLOG-14661

BACKLOG-14661: Missing label, display mapping field

---

src/main/java/org/jahia/modules/saml2/actions/SAMLCallback.java

https://jira.jahia.org/browse/BACKLOG-14765

BACKLOG-14765: fixed mapping on existing users

---

src/main/resources/javascript/saml/saml-controller.js

https://jira.jahia.org/browse/BACKLOG-14421

BACKLOG-14421: Allow only one callback URL

---

src/main/java/org/jahia/modules/saml2/actions/MetadataAction.java
src/main/resources/META-INF/spring/saml-authentication-valve.xml
src/main/resources/javascript/saml/saml-controller.js

https://jira.jahia.org/browse/BACKLOG-14835

BACKLOG-14835: Fixed link, permission and metadata content

---

src/main/java/org/jahia/modules/saml2/SamlConnector.java

https://jira.jahia.org/browse/BACKLOG-14836

BACKLOG-14836: reset after save

---

src/main/java/org/jahia/modules/saml2/actions/MetadataAction.java

https://jira.jahia.org/browse/BACKLOG-14835

BACKLOG-14835: Fixed metadata content

---

.circleci/.circleci.settings.xml
.circleci/config.yml
.github/workflows/triggerReleaseAction.yml

https://jira.jahia.org/browse/SELENIUM-1509
Try to fix failing merge pipeline; Update circle CI configuration
- copy-paste from jahia-authentication circle ci config
- update module references and update ssh key fingerprint

Update Circle CI configuration

---

.circleci/config.yml
.circleci/owasp-suppressions.xml
pom.xml
src/main/java/org/jahia/modules/saml2/SamlConnector.java
src/main/java/org/jahia/modules/saml2/actions/ConnectToSAML.java
src/main/java/org/jahia/modules/saml2/actions/SAMLCallback.java

https://jira.jahia.org/browse/QA-14097
Update vulnerable dependencies, but stay compatible with JDK 8

QA-14097: Update to highest dependency still compatible with JDK 8

---

src/main/java/org/jahia/modules/saml2/SAML2Util.java

https://jira.jahia.org/browse/QA-14302
Improved the code to retrieve correct port information. Change is consistent with v2.0 of this module.

Fix to retrieve server port.

---

pom.xml
src/main/java/org/jahia/modules/saml2/SamlConnector.java
src/main/java/org/jahia/modules/saml2/actions/SAMLCallback.java
src/main/resources/META-INF/spring/saml-authentication-valve.xml

QA-14537: Implements ConnectorResultProcessor (#54)

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-20285

BACKLOG-20285 : upgrade jahia version

---

.github/dependabot.yml

https://jira.jahia.org/browse/TECH-1127
Add dependabot config

TECh-1127 Add dependabot config

---

.github/workflows/nightly.yml

The reporter path was incorrect

Fixed path for the test report

---

pom.xml

https://jira.jahia.org/browse/TECH-1256
Upgrade xalan from 2.7.2 to 2.7.3

TECH-1256: Upgrade Xalan

---

src/main/java/org/jahia/modules/saml2/actions/ConnectToSAML.java

https://jira.jahia.org/browse/QA-14841
Incorrect path for the cookie redirect preventing its retrieval and the expected redirection. In addition,cookie is not secured when HTTPS connection is being used.

QA-14841: SAML, incorrect values for cookie redirect (path and flag secure)

---

.github/workflows/on-release.yml
pom.xml

https://jira.jahia.org/browse/BACKLOG-21049

BACKLOG-21049 - Update parent version

---

src/main/java/org/jahia/modules/saml2/actions/SAMLCallback.java

https://jira.jahia.org/browse/QA-14958

QA-14958: Fix saml callback not working if url has parameters

---

.github/workflows/nightly.yml

Added manual execution to nightly

---

.github/workflows/nightly-standalone-release.yml
.github/workflows/nightly-standalone-snapshot.yml
.github/workflows/on-code-change.yml
.github/workflows/on-merge.yml
pom.xml
tests/provisioning-manifest-release.yml

https://jira.jahia.org/browse/QA-14958

QA-14958: Downgrade parent version to 8.1.3.0

---

.github/workflows/nightly-standalone-snapshot.yml

https://jira.jahia.org/browse/QA-14958

QA-14958: Fix wrong jahia image for snapshot

---

.github/workflows/nightly-standalone-release.yml
.github/workflows/nightly-standalone-snapshot.yml

Split pagerduty reporting between Jahia RL and Jahia SN

---

src/main/resources/META-INF/configurations/org.jahia.modules.jahiacsrfguard-saml.cfg
src/main/resources/META-INF/spring/saml-authentication-valve.xml

https://jira.jahia.org/browse/QA-14996

QA-14996 whitelist ConnectToSAML action

---

.github/workflows/schedule-sonar.yml
pom.xml

https://jira.jahia.org/browse/TECH-1395
Exclude already provided transitive dependencies as they lead to false entries in the SBOM.

TECH-1395: Prevent false entries in module SBOM

---

pom.xml

https://jira.jahia.org/browse/TECH-1395
Also add exclusions for guava as the provided one is used now

TECH-1395: Also add exclusions for guava as the provided one is used

---

tests/provisioning-manifest-build-8.2.x.yml
tests/provisioning-manifest-snapshot-8.2.x.yml

https://jira.jahia.org/browse/TECH-1611
See title

TECH-1611: Add grid and tabularList in the provisioning scripts

---

.github/workflows/nightly-standalone-release.yml
.github/workflows/nightly-standalone-snapshot.yml
.github/workflows/on-code-change.yml
.github/workflows/on-merge.yml
.github/workflows/on-release.yml
.github/workflows/on-rollback.yml
.github/workflows/schedule-sonar.yml

https://jira.jahia.org/browse/TECH-1639
Upgrade actions

TECH-1639 Upgrade actions

---

pom.xml

https://jira.jahia.org/browse/SEC-110

SEC-110: Exclude commons-io to enforce usage of the Jahia core version
